database:
    user: root
    password: password
    url: jdbc:mysql://localhost:3306/bytecraft?autoReconnect=true
support:
    user: bytecraft.staff@gmail.com
    password: notinherelololol
    to: 
        - sabersamus@gmail.com
spawn:
    world: 64, 64, 64, 1, 1
motd: 'Welcome to Bytecraft! If no staff members are online, please try again later? :D'